// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistOrderRequest struct {
	CustomerID           string   `protobuf:"bytes,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistOrderRequest) Reset()         { *m = RegistOrderRequest{} }
func (m *RegistOrderRequest) String() string { return proto.CompactTextString(m) }
func (*RegistOrderRequest) ProtoMessage()    {}
func (*RegistOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *RegistOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistOrderRequest.Unmarshal(m, b)
}
func (m *RegistOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistOrderRequest.Marshal(b, m, deterministic)
}
func (m *RegistOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistOrderRequest.Merge(m, src)
}
func (m *RegistOrderRequest) XXX_Size() int {
	return xxx_messageInfo_RegistOrderRequest.Size(m)
}
func (m *RegistOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistOrderRequest proto.InternalMessageInfo

func (m *RegistOrderRequest) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

type RegistOrderResponse struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistOrderResponse) Reset()         { *m = RegistOrderResponse{} }
func (m *RegistOrderResponse) String() string { return proto.CompactTextString(m) }
func (*RegistOrderResponse) ProtoMessage()    {}
func (*RegistOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *RegistOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistOrderResponse.Unmarshal(m, b)
}
func (m *RegistOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistOrderResponse.Marshal(b, m, deterministic)
}
func (m *RegistOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistOrderResponse.Merge(m, src)
}
func (m *RegistOrderResponse) XXX_Size() int {
	return xxx_messageInfo_RegistOrderResponse.Size(m)
}
func (m *RegistOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistOrderResponse proto.InternalMessageInfo

func (m *RegistOrderResponse) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func init() {
	proto.RegisterType((*RegistOrderRequest)(nil), "order.RegistOrderRequest")
	proto.RegisterType((*RegistOrderResponse)(nil), "order.RegistOrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x2f, 0x4a, 0x49,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x4c, 0xb8, 0x84, 0x82,
	0x52, 0xd3, 0x33, 0x8b, 0x4b, 0xfc, 0x41, 0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x39, 0x2e, 0xae, 0xe4, 0xd2, 0xe2, 0x92, 0xfc, 0xdc, 0xd4, 0x22, 0x4f, 0x17, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x25, 0x7d, 0x2e, 0x61, 0x14, 0x5d, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0x60, 0x53, 0xe1, 0x7a, 0x60, 0x5c, 0xa3, 0x30, 0x2e, 0x1e,
	0xb0, 0xd2, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x37, 0x2e, 0x6e, 0x24, 0x03, 0x84,
	0x24, 0xf5, 0x20, 0x4e, 0xc3, 0x74, 0x8a, 0x94, 0x14, 0x36, 0x29, 0x88, 0x7d, 0x4a, 0x0c, 0x49,
	0x6c, 0x60, 0xcf, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x69, 0x93, 0xd6, 0x35, 0xdb, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	RegistOrder(ctx context.Context, in *RegistOrderRequest, opts ...grpc.CallOption) (*RegistOrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) RegistOrder(ctx context.Context, in *RegistOrderRequest, opts ...grpc.CallOption) (*RegistOrderResponse, error) {
	out := new(RegistOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/RegistOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	RegistOrder(context.Context, *RegistOrderRequest) (*RegistOrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) RegistOrder(ctx context.Context, req *RegistOrderRequest) (*RegistOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_RegistOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).RegistOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/RegistOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).RegistOrder(ctx, req.(*RegistOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistOrder",
			Handler:    _OrderService_RegistOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
