version: '3'

services:
  flyway:
    image: flyway/flyway:6.1.4-alpine
    command: migrate
    environment:
        FLYWAY_URL: jdbc:postgresql://database/pg-go-lesson
        FLYWAY_USER: admin
        FLYWAY_PASSWORD: admin
        # FLYWAY_SCHEMAS: myschema
        FLYWAY_CONNECT_RETRIES: 60
    volumes:
        - ./postgres/migrations:/flyway/sql
    depends_on:
        - database
  database:
    image: postgres:11-alpine
    container_name: pg-go-lesson
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pg-go-lesson
    # volumes:
    #   - ./postgres/init:/docker-entrypoint-initdb.d
