version: '3'

services:
  db:
    image: postgres:11-alpine
    container_name: pg-go-lesson
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pg-go-lesson
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
